# Generated by Django 2.1.2 on 2018-10-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('re_encryption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='records_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='re_encryption.RecordsSet'),
        ),
    ]
