# Generated by Django 2.1.2 on 2018-10-19 08:01

import data_office.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('eth_address', data_office.fields.ETHAddressField(max_length=42)),
                ('pub_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('eth_address', data_office.fields.ETHAddressField(max_length=42)),
                ('pub_key', models.CharField(max_length=100)),
                ('data_sets', models.ManyToManyField(related_name='recepients', to='data_office.DataSet')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='data_office.Patient'),
        ),
    ]
