# Generated by Django 2.1.2 on 2018-10-24 09:12

import data_office.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', data_office.models.fields.ETHAddressField(max_length=42)),
                ('pub_key', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_id', models.CharField(max_length=100)),
                ('eth_address', data_office.models.fields.ETHAddressField(max_length=42)),
                ('pub_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data', models.BinaryField()),
                ('capsule', models.BinaryField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_sets', to='data_office.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='recepient',
            name='records_sets',
            field=models.ManyToManyField(related_name='recepients', to='data_office.RecordsSet'),
        ),
        migrations.AddField(
            model_name='recepient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to=settings.AUTH_USER_MODEL),
        ),
    ]
